In [1]:
from pycaret.classification import * #Importing Relevant Libraries

In [3]:
import pandas as pd #Importing relevant library

In [4]:
df=pd.read_csv("cleaned_rebalanced_booking_cancellation2b.csv") #Loading the cleaned and preprocessed dataset

In [5]:
df.head() #Dataset overview

,number of adults,number of children,number of weekend nights,number of week nights,type of meal,car parking space,room type,lead time,market segment type,repeated,average price,special requests,booking status
0,-1.629573,2.267436,1.369817,2.187052,0,0,0,1.716208,3,0,-0.481091,-0.787847,1
1,-1.629573,-0.265642,0.216935,0.634389,3,0,0,-0.965514,4,0,0.112271,0.483800,1
2,0.298217,2.267436,0.216935,0.634389,0,0,0,-1.014495,4,0,-1.688144,-0.787847,0
3,-1.629573,-0.265642,-0.935946,-0.141943,0,0,0,1.557019,4,0,-0.099916,0.483800,0
4,-1.629573,-0.265642,0.216935,-0.141943,3,0,0,-0.438966,4,0,-0.830501,-0.787847,0

In [6]:
clf_setup=setup(data=df,target="booking status",normalize=True,session_id=42)  #Initializing Pycaret

In [7]:
best_model=compare_models(cross_validation=False,sort='f1') #comparing models and selecting the best one

In [8]:
print(best_model)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, n_estimators=100, n_jobs=-1,
                       oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [9]:
tuned_model=tune_model(best_model,optimize="f1",fold=5) #Fine-tuning the best model

Fitting 5 folds for each of 10 candidates, totalling 50 fits
Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

In [10]:
final_model=finalize_model(tuned_model) #Original model was better than tuned model

In [13]:
save_model(final_model,"final_model_booking_cancellation_prediction")  #Saving the final model

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['number of adults',
                                              'number of children',
                                              'number of weekend nights',
                                              'number of week nights',
                                              'type of meal',
                                              'car parking space', 'room type',
                                              'lead time', 'market segment type',
                                              'repeated', 'average price',
                                              'special requests'],
                                     transformer=SimpleImputer(add_indicator=Fals...
                  RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                         class_weight=None, criterion='gini',
                                         max_depth=None, max_features='sqrt',
                                         max_leaf_nodes=None, max_samples=None,
                                         min_impurity_decrease=0.0,
                                         min_samples_leaf=1, min_samples_split=2,
                                         min_weight_fraction_leaf=0.0,
                                         monotonic_cst=None, n_estimators=100,
                                         n_jobs=-1, oob_score=False,
                                         random_state=42, verbose=0,
                                         warm_start=False))],
          verbose=False),
 'final_model_booking_cancellation_prediction.pkl')